# name: Update sn32_master_openrgb after sn32_master merge
name: Update didstopia/keychron_k8_openrgb after didstopia/keychron_k8 merge

on:
  push:
    branches:
    - sn32_master
    - didstopia/keychron_k8
    # - didstopia/keychron_k8_openrgb
  workflow_dispatch:

jobs:
  develop_update:
    runs-on: ubuntu-latest

    # if: github.repository == 'SonixQMK/qmk_firmware'
    if: github.repository == 'Didstopia/qmk_firmware'

    steps:
    - uses: actions/checkout@v3
    #   with:
    #     fetch-depth: 0

    # - name: Checkout develop
    #   run: |-
    #     set -x
    #     # git fetch origin sn32_master sn32_master_openrgb
    #     git fetch origin didstopia/keychron_k8 didstopia/keychron_k8_openrgb
    #     # git checkout sn32_master_openrgb
    #     git checkout didstopia/keychron_k8

    - name: Check if branch locked
      id: check_locked
      uses: andstor/file-existence-action@v1
      with:
        files: ".locked"

    - name: Update openrgb from master
      if: steps.check_locked.outputs.files_exists == 'false'
      run: |-
        set -x
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # FIXME: This is still all kinds of broken..
        git fetch --prune
        git branch --all
        git checkout didstopia/keychron_k8_openrgb
        git merge didstopia/keychron_k8
        git push
        # # git merge origin/sn32_master
        # git merge origin/didstopia/keychron_k8
        # # git push origin sn32_master_openrgb
        # git push origin didstopia/keychron_k8_openrgb
